# Generated by Django 3.1.3 on 2020-11-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=400)),
                ('image_path', models.CharField(max_length=400)),
                ('title', models.CharField(max_length=400)),
                ('source', models.CharField(max_length=400)),
            ],
        ),
    ]
