# Generated by Django 3.1.3 on 2020-11-21 23:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 59, 17, 299561, tzinfo=utc)),
        ),
    ]
