# Generated by Django 3.1.3 on 2020-11-22 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20201121_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 16, 0, 40, 377543)),
        ),
    ]
