# top players
names = {
	'Christian McCaffrey': ['CAR', 'RB1'],
	'Saquon Barkley': ['NYG', 'RB2'],
	'Ezekiel Elliott': ['DAL', 'RB3'],
	'Derrick Henry': ['TEN', 'RB4'],
	'Dalvin Cook': ['MIN', 'RB5'],
	'Alvin Kamara': ['NO', 'RB6'],
	'Josh Jacobs': ['LV', 'RB7'],
	'Joe Mixon': ['CIN', 'RB8'],
	'Michael Thomas': ['NO', 'WR1'],
	'Nick Chubb': ['CLE', 'RB9'],
	'Clyde Edwards-Helaire': ['KC', 'RB10'],
	'Davante Adams': ['GB', 'WR2'],
	'Tyreek Hill': ['KC', 'WR3'],
	'Julio Jones': ['ATL', 'WR4'],
	'Travis Kelce': ['KC', 'TE1'],
	'Aaron Jones': ['GB', 'RB11'],
	'Miles Sanders': ['PHI', 'RB12'],
	'George Kittle': ['SF', 'TE2'],
	'Chris Godwin': ['TB', 'WR5'],
	'Kenyan Drake': ['ARI', 'RB13'],
	'Kenny Golladay': ['DET', 'WR6'],
	'DeAndre Hopkins': ['ARI', 'WR7'],
	'Patrick Mahomes II': ['KC', 'QB1'],
	'Austin Ekeler': ['LAC', 'RB14'],
	'Mike Evans': ['TB', 'WR8'],
	'Mark Andrews': ['BAL', 'TE3'],
	'Chris Carson': ['SEA', 'RB15'],
	'A.J. Brown': ['TEN', 'WR9'],
	'Allen Robinson II': ['CHI', 'WR10'],
	'Adam Thielen': ['MIN', 'WR11'],
	'Lamar Jackson': ['BAL', 'QB2'],
	'James Conner': ['PIT', 'RB16'],
	'D.J. Moore': ['CAR', 'WR12'],
	'Odell Beckham Jr.': ['CLE', 'WR13'],
	'Amari Cooper': ['DAL', 'WR14'],
	'Todd Gurley II': ['ATL', 'RB17'],
	'JuJu Smith-Schuster': ['PIT', 'WR15'],
	'Calvin Ridley': ['ATL', 'WR16'],
	'Robert Woods': ['LAR', 'WR17'],
	'Jonathan Taylor': ['IND', 'RB18'],
	'Cooper Kupp': ['LAR', 'WR18'],
	'Terry McLaurin': ['WAS', 'WR19'],
	'David Johnson': ['HOU', 'RB19'],
	'Tyler Lockett': ['SEA', 'WR20'],
	'D.K. Metcalf': ['SEA', 'WR21'],
	'Zach Ertz': ['PHI', 'TE4'],
	'D.J. Chark Jr.': ['JAC', 'WR22'],
	'Melvin Gordon III': ['DEN', 'RB20'],
	'Mark Ingram II': ['BAL', 'RB21'],
	'Courtland Sutton': ['DEN', 'WR23'],
	'Raheem Mostert': ['SF', 'RB22'],
	"Le'Veon Bell": ['KC', 'RB23'],
	'Dak Prescott': ['DAL', 'QB3'],
	'Keenan Allen': ['LAC', 'WR24'],
	'Russell Wilson': ['SEA', 'QB4'],
	'DeVante Parker': ['MIA', 'WR25'],
	'Darren Waller': ['LV', 'TE5'],
	'T.Y. Hilton': ['IND', 'WR26'],
	'Stefon Diggs': ['BUF', 'WR27'],
	'Michael Gallup': ['DAL', 'WR28'],
	'Deshaun Watson': ['HOU', 'QB5'],
	'Cam Akers': ['LAR', 'RB24'],
	'Kyler Murray': ['ARI', 'QB6'],
	'David Montgomery': ['CHI', 'RB25'],
	'Marquise Brown': ['BAL', 'WR29'],
	'Jarvis Landry': ['CLE', 'WR30'],
	'A.J. Green': ['CIN', 'WR31'],
	'Leonard Fournette': ['TB', 'RB26'],
	'Evan Engram': ['NYG', 'TE6'],
	'Will Fuller V': ['HOU', 'WR32'],
	'Tyler Boyd': ['CIN', 'WR33'],
	'Matt Ryan': ['ATL', 'QB7'],
	'Josh Allen': ['BUF', 'QB8'],
	'Marvin Jones Jr.': ['DET', 'WR34'],
	'Devin Singletary': ['BUF', 'RB27'],
	'Kareem Hunt': ['CLE', 'RB28'],
	'Julian Edelman': ['NE', 'WR35'],
	'Hunter Henry': ['LAC', 'TE7'],
	'Jordan Howard': ['MIA', 'RB29'],
	'Tyler Higbee': ['LAR', 'TE8'],
	"D'Andre Swift": ['DET', 'RB30'],
	'Carson Wentz': ['PHI', 'QB9'],
	'Drew Brees': ['NO', 'QB10'],
	'J.K. Dobbins': ['BAL', 'RB31'],
	'Hayden Hurst': ['ATL', 'TE9'],
	'Brandin Cooks': ['HOU', 'WR36'],
	'Zack Moss ': ['BUF', 'RB32'],
	'Tom Brady': ['TB', 'QB11'],
	'Diontae Johnson': ['PIT', 'WR37'],
	'Matthew Stafford ': ['DET', 'QB12'],
	'Deebo Samuel': ['SF', 'WR38'],
	'Jared Cook': ['NO', 'TE10'],
	'Antonio Gibson': ['WAS', 'RB33'],
	'Marlon Mack': ['IND', 'RB34'],
	'Jamison Crowder': ['NYJ', 'WR39'],
	'John Brown': ['BUF', 'WR40'],
	'Aaron Rodgers': ['GB', 'QB13'],
	'Christian Kirk': ['ARI', 'WR41'],
	'Phillip Lindsay': ['DEN', 'RB35'],
	'CeeDee Lamb': ['DAL', 'WR42'],
	'Darius Slayton': ['NYG', 'WR43'],
	'Rob Gronkowski': ['TB', 'TE11'],
	'Cam Newton': ['NE', 'QB14'],
	'Ronald Jones II': ['TB', 'RB36'],
	'Daniel Jones': ['NYG', 'QB15'],
	'Ben Roethlisberger': ['PIT', 'QB16'],
	'Sterling Shepard': ['NYG', 'WR44'],
	'Matt Breida': ['MIA', 'RB37'],
	'Sony Michel': ['NE', 'RB38'],
	'James White': ['NE', 'RB39'],
	'Tevin Coleman': ['SF', 'RB40'],
	'Mike Gesicki': ['MIA', 'TE12'],
	'Jared Goff': ['LAR', 'QB17'],
	'Austin Hooper': ['CLE', 'TE13'],
	'Latavius Murray': ['NO', 'RB41'],
	'Noah Fant': ['DEN', 'TE14'],
	'Anthony Miller': ['CHI', 'WR45'],
	'T.J. Hockenson': ['DET', 'TE15'],
	'Henry Ruggs III': ['LV', 'WR46'],
	'Preston Williams': ['MIA', 'WR47'],
	'Jonnu Smith': ['TEN', 'TE16'],
	'Dallas Goedert': ['PHI', 'TE17'],

	}


