# Generated by Django 3.1.4 on 2021-01-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_player_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
